# Copyright (c) the IW4x authors (see the AUTHORS file).
# SPDX-License-Identifier: GPL-3.0-only WITH AdditionRef-IW4x-Exception-1.1

define cli: file
cli{*}: extension = cli

define css: file
css{*}: extension = css

define xhtml: doc
xhtml{*}: extension = xhtml

# The documentation sources. Note that file{} targets (and the cli{} and css{}
# targets derived from it) are distributed but not installed.
#
./: cli{headers manual} file{man-* doc-*} style/{css{*} file{LICENSE}}

# The man page and the manual are generated with the CLI compiler in the
# development build and distributed, so that the consumption build gets them
# without it. They are never kept in the repository.
#

## Consumption build ($develop == false).
#

# Use the pregenerated versions, which only the distribution has.
#
./: pregenerated/{man1 xhtml}{*}: include = (!$develop)

# Distribute the pregenerated versions only in the consumption build.
#
pregenerated/{man1 xhtml}{*}: dist = (!$develop)

#
##

## Development build ($develop == true).
#

./: man1{headers} xhtml{headers headers-manual}: include = $develop

if $develop
{
  import! [metadata] cli = cli%exe{cli}

  # Use the date of the last commit, so that the same revision always
  # produces the same documentation.
  #
  doc_date = $process.run(git -C $src_root log -1 '--format=%cd' \
                          '--date=format:%B %Y')

  doc_options = -v project=headers -v version=$version        \
                -v copyright='the IW4x authors' -v date="$doc_date" \
                --suppress-undocumented

  # The manifest format is described in the build2 package manager manual.
  #
  bpkg_manual = 'https://build2.org/bpkg/doc/build2-package-manager-manual.xhtml'
}

# In the development build distribute the generated versions, remapping their
# locations to the paths of the pregenerated versions (which are only
# distributed in the consumption build, see above).
#
man1{headers} xhtml{headers headers-manual}: \
  dist = ($develop ? pregenerated/ : false)

man1{headers}: cli{headers} file{man-prologue.1 man-epilogue.1} $cli
%
if $develop
{{
  diag 'cli --man' ($<[0]) -> $>

  $cli $doc_options --generate-man --ascii-tree \
    --man-prologue-file $path($<[1])                     \
    --man-epilogue-file $path($<[2])                     \
    --link-regex '%bpkg(#.+)?%$1%'                       \
    --stdout $path($<[0]) >$path($>)
}}

xhtml{headers}: cli{headers} file{man-prologue.xhtml man-epilogue.xhtml} \
                style/css{common pre-box man} $cli
%
if $develop
{{
  diag 'cli --html' ($<[0]) -> $>

  $cli $doc_options --generate-html --html-suffix .xhtml \
    --html-prologue-file $path($<[1])                    \
    --html-epilogue-file $path($<[2])                    \
    --link-regex "%bpkg\(#.+\)?%$bpkg_manual\$1%"        \
    --stdout $path($<[0]) >$path($>)
}}

xhtml{headers-manual}: cli{manual}                                      \
                       file{doc-prologue.xhtml doc-epilogue.xhtml}      \
                       style/css{common pre-box code-box p-code-box toc \
                                 doc}                                    \
                       $cli
%
if $develop
{{
  diag 'cli --html' ($<[0]) -> $>

  $cli $doc_options --generate-html --html-suffix .xhtml \
    --html-prologue-file $path($<[1])                    \
    --html-epilogue-file $path($<[2])                    \
    --link-regex "%bpkg\(#.+\)?%$bpkg_manual\$1%"        \
    --stdout $path($<[0]) >$path($>)
}}
